### ISSUE TITLE
Change "\n" to PHP_EOL for Windows users

### ISSUE THREAD

**Issue by 1e1** [hoaproject/Cli#16]
I noticed `Cli/Bin/Welcome.php` use `\n` char for printing new line in the Console. 
The Best Practice is [`PHP_EOL`](http://php.net/manual/en/reserved.constants.php#constant.php-eol), as `DIRECTORY_SEPARATOR` for `/`.
It causes some unexpected issues while we share our code to Windows users ;)

**Comment by Hywan** [comment]
@camael24 Did you met any issues with `hoa/cli` on Windows? Personnally, not.

**Comment by Hywan** [comment]
@1e1 Did you met any issues?

**Comment by 1e1** [comment]
I don't use Windows ;)
But it's a [best pratice for End Of Line](http://php.net/manual/en/reserved.constants.php#constant.php-eol). 
I remember a PHP SDK (not using Hoa) which had some complications on Windows with CURL and certificates due to hard coded "\n" and "/". 
Ok, it is not the same context, but goto line 2 ;)

**Comment by Hywan** [comment]
But today, Windows understands both `/` and `\` and handles correctly CRLF in the console or file. I would like real bugs to change it :-).

**Comment by 1e1** [comment]
Well… I can close this ticket :p

**Comment by Hywan** [comment]
Please do. I would be glad to re-open it if a bug occurs.
